services:
  - type: web
    name: e-commerce-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ENVIRONMENT
        value: prod
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URL
        sync: false

databases:
  - name: e-commerce-mongodb
    databaseName: ecommerce
    plan: free