services:
  # Web service
  - type: web
    name: e-commerce-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ENVIRONMENT
        value: prod
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URL
        fromDatabase:
          name: e-commerce-mongodb
          property: connectionString

databases:
  # MongoDB database
  - name: e-commerce-mongodb
    plan: free
    databaseName: ecommerce
    ipAllowList: [] # allow all IPs during development, restrict for production